'use strict';
const $=id=>document.getElementById(id);let state,selected=null,language='zh',dirty=false,busy=false;
const MAIN_SITE_BASE='https://homepage.ntu.edu.tw/~jour/';
const emptyLocale=()=>({visible:false,title:'',tag:'',excerpt:'',bodyHtml:'',externalUrl:''});
const current=()=>state?.data.records.find(item=>item.id===selected);
let tagValues=[],tagOptions=[],activeTagOption=-1;
function parseTags(value){const seen=new Set();return String(value||'').split(/[、,，;；\n]+/).map(tag=>tag.trim().replace(/^#+/, '')).filter(tag=>{const key=tag.toLocaleLowerCase();if(!tag||seen.has(key))return false;seen.add(key);return true})}
function syncTagValue(){$('tag').value=tagValues.join('、')}
function allTags(){const seen=new Set(),tags=[];(state?.data.records||[]).forEach(item=>Object.values(item.locales||{}).forEach(loc=>parseTags(loc?.tag).forEach(tag=>{const key=tag.toLocaleLowerCase();if(!seen.has(key)){seen.add(key);tags.push(tag)}})));return tags.sort((a,b)=>a.localeCompare(b,'zh-Hant'))}
function closeTagSuggestions(){tagOptions=[];activeTagOption=-1;$('tag-suggestions').hidden=true;$('tag-suggestions').replaceChildren();$('tag-input').setAttribute('aria-expanded','false');$('tag-input').removeAttribute('aria-activedescendant')}
function selectTagOption(index){activeTagOption=index;document.querySelectorAll('.tag-suggestion').forEach((option,i)=>{option.dataset.active=String(i===index);option.setAttribute('aria-selected',String(i===index))});const option=$(`tag-option-${index}`);if(option)$('tag-input').setAttribute('aria-activedescendant',option.id)}
function showTagSuggestions(){const query=$('tag-input').value.trim().replace(/^#+/, '').toLocaleLowerCase(),selectedKeys=new Set(tagValues.map(tag=>tag.toLocaleLowerCase()));tagOptions=allTags().filter(tag=>!selectedKeys.has(tag.toLocaleLowerCase())&&(!query||tag.toLocaleLowerCase().includes(query))).sort((a,b)=>{const aStart=a.toLocaleLowerCase().startsWith(query),bStart=b.toLocaleLowerCase().startsWith(query);return Number(bStart)-Number(aStart)||a.localeCompare(b,'zh-Hant')}).slice(0,8);if(!tagOptions.length){closeTagSuggestions();return}activeTagOption=-1;const options=tagOptions.map((tag,index)=>{const option=document.createElement('button');option.type='button';option.id=`tag-option-${index}`;option.className='tag-suggestion';option.setAttribute('role','option');option.setAttribute('aria-selected','false');option.textContent=tag;option.addEventListener('mousedown',event=>event.preventDefault());option.addEventListener('click',()=>addTag(tag));return option});$('tag-suggestions').replaceChildren(...options);$('tag-suggestions').hidden=false;$('tag-input').setAttribute('aria-expanded','true');$('tag-input').removeAttribute('aria-activedescendant')}
function renderTags(){const chips=tagValues.map((tag,index)=>{const chip=document.createElement('span');chip.className='tag-chip';const label=document.createElement('span');label.textContent=tag;const remove=document.createElement('button');remove.type='button';remove.className='tag-remove';remove.setAttribute('aria-label',`移除標籤 ${tag}`);remove.textContent='×';remove.addEventListener('click',()=>{tagValues.splice(index,1);syncTagValue();renderTags();setDirty();$('tag-input').focus();showTagSuggestions()});chip.append(label,remove);return chip});$('tag-chips').replaceChildren(...chips);syncTagValue();$('tag-editor').dataset.empty=String(!tagValues.length)}
function setTags(value){tagValues=parseTags(value);$('tag-input').value='';renderTags();closeTagSuggestions()}
function addTag(value){const values=parseTags(value);let changed=false;values.forEach(tag=>{if(!tagValues.some(currentTag=>currentTag.toLocaleLowerCase()===tag.toLocaleLowerCase())){tagValues.push(tag);changed=true}});$('tag-input').value='';renderTags();closeTagSuggestions();if(changed)setDirty();$('tag-input').focus()}
function commitTagInput(){const value=$('tag-input').value.trim();if(value)addTag(value);else closeTagSuggestions()}
function previewImageUrl(value){const path=String(value||'').trim();if(!path||/^https?:\/\//i.test(path))return path;return MAIN_SITE_BASE+path.replace(/^\/+/, '')}
function setStatus(message,error=false){$('status').textContent=message;$('status').dataset.error=String(error)}
function setDirty(value=true){dirty=value;controls();releaseState()}
function controls(){$('publish').disabled=busy||dirty||!state;$('reload').disabled=busy;$('save').disabled=busy||!dirty;$('add').disabled=busy;document.querySelectorAll('#news-form input,#news-form select,#news-form textarea,#news-form button').forEach(e=>e.disabled=busy)}
function releaseState(){if(!state)return;const matched=!dirty&&state.current&&state.current.draftVersion===state.version;$('release-state').textContent=matched?'草稿已發布':'有尚未發布的草稿';$('release-state').dataset.pending=String(!matched)}
function badge(lang,visible){const b=document.createElement('span');b.className='language-state';b.dataset.visible=String(visible);b.textContent=`${lang==='zh'?'中文':'英文'}：${visible?'發布':'草稿'}`;return b}
function text(parent,cls,value){const d=document.createElement('div');d.className=cls;d.textContent=value||'—';parent.append(d)}
function matches(item){const collection=$('collection-filter').value;if(collection&&item.collection!==collection)return false;const filter=$('language-filter').value;if(filter==='zh'&&!item.locales.zh.visible)return false;if(filter==='en'&&!item.locales.en.visible)return false;if(filter==='draft'&&(item.locales.zh.visible||item.locales.en.visible))return false;const q=$('search').value.trim().toLowerCase();return !q||[item.date,item.collection,item.locales.zh.title,item.locales.zh.tag,item.locales.zh.excerpt,item.locales.en.title,item.locales.en.tag,item.locales.en.excerpt].join(' ').toLowerCase().includes(q)}
function render(){const records=[...state.data.records].sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.date.localeCompare(a.date)||a.id.localeCompare(b.id));const rows=records.filter(matches).map(item=>{const tr=document.createElement('tr');tr.tabIndex=0;tr.dataset.id=item.id;const date=document.createElement('td');text(date,'primary-data',item.date);text(date,'news-tag',item.collection==='activities'?'活動資訊':'最新消息');if(item.pinned)text(date,'news-tag','置頂');const image=document.createElement('td');if(item.image){const img=document.createElement('img');img.className='news-thumb';img.src=previewImageUrl(item.image);img.alt='';image.append(img)}const zh=document.createElement('td');text(zh,'news-title',item.locales.zh.title);text(zh,'news-tag',item.locales.zh.tag);text(zh,'news-excerpt',item.locales.zh.excerpt);const en=document.createElement('td');text(en,'news-title',item.locales.en.title);text(en,'news-tag',item.locales.en.tag);text(en,'news-excerpt',item.locales.en.excerpt);const status=document.createElement('td');const stack=document.createElement('div');stack.className='publish-stack';stack.append(badge('zh',item.locales.zh.visible),badge('en',item.locales.en.visible));status.append(stack);const action=document.createElement('td');const button=document.createElement('button');button.type='button';button.className='edit-button';button.textContent='編輯';action.append(button);tr.append(date,image,zh,en,status,action);tr.addEventListener('click',()=>open(item.id,true));tr.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(item.id,true)}});return tr});$('news-rows').replaceChildren(...rows);$('empty-result').hidden=rows.length>0;$('total-count').textContent=records.length;$('zh-count').textContent=records.filter(r=>r.locales.zh.visible).length;$('en-count').textContent=records.filter(r=>r.locales.en.visible).length}
function capture(){const item=current();if(!item)return;item.collection=$('collection').value;item.date=$('date').value;item.pinned=$('pinned').checked;item.image=$('image').value.trim();const loc=item.locales[language];loc.visible=$('visible').checked;loc.title=$('title').value;loc.tag=$('tag').value;loc.excerpt=$('excerpt').value;loc.externalUrl=$('external-url').value.trim();loc.bodyHtml=$('body-editor').innerHTML}
function syncLanguageTabs(){document.querySelectorAll('.language-tab').forEach(tab=>{const active=tab.dataset.language===language;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1});$('language-panel').setAttribute('aria-labelledby',`language-tab-${language}`)}
function switchLanguage(next){if(next===language)return;capture();language=next;fill()}
function languageTabKeydown(event){if(!['ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();const tabs=[...document.querySelectorAll('.language-tab')],step=event.key==='ArrowRight'?1:-1,next=tabs[(tabs.indexOf(event.currentTarget)+step+tabs.length)%tabs.length];next.focus();switchLanguage(next.dataset.language)}
function fill(){const item=current(),loc=item.locales[language];$('collection').value=item.collection;$('date').value=item.date;$('pinned').checked=item.pinned;$('image').value=item.image;$('visible').checked=loc.visible;$('visible-label').textContent=language==='zh'?'發布到中文網站':'Publish on English website';$('title').value=loc.title;setTags(loc.tag);$('excerpt').value=loc.excerpt;$('external-url').value=loc.externalUrl;$('body-editor').innerHTML=loc.bodyHtml;$('editor-name').textContent=item.locales.zh.title||item.locales.en.title||'未命名資料';$('editor-id').textContent=(item.collection==='activities'?'活動資訊 · ':'最新消息 · ')+item.id;$('body-length').textContent=`${$('body-editor').textContent.length.toLocaleString()} 個字元`;$('image-upload').value='';syncLanguageTabs()}
function showList(push=false){if(dirty&&!confirm('返回清單會放棄尚未儲存的變更，確定繼續？'))return;dirty=false;selected=null;$('editor-view').hidden=true;$('directory-view').hidden=false;render();if(push)history.pushState({},'',location.pathname);controls()}
function open(id,push=false){if(dirty&&selected!==id&&!confirm('切換消息會放棄尚未儲存的變更，確定繼續？'))return;selected=id;language='zh';dirty=false;$('directory-view').hidden=true;$('editor-view').hidden=false;fill();if(push){const u=new URL(location.href);u.searchParams.set('id',id);history.pushState({},'',u)}controls();scrollTo(0,0)}
async function api(path,method='GET',data){const response=await fetch('/news-admin/api/'+path,{method,headers:{'Content-Type':'application/json','X-News-Request':'1'},body:data?JSON.stringify(data):undefined,cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error||'請求失敗');return value}
async function perform(fn){if(busy)return;busy=true;controls();try{await fn()}catch(error){setStatus(error.message,true)}finally{busy=false;controls()}}
async function load(){state=await api('draft');if(!state.data)throw new Error('尚未匯入消息資料。');state.data.records.forEach(item=>{if(!item.collection)item.collection='news'});setDirty(false);const id=new URL(location.href).searchParams.get('id');if(id&&state.data.records.some(r=>r.id===id))open(id);else showList();setStatus('已載入消息與活動草稿。')}
$('news-form').addEventListener('input',e=>{if(e.target.id!=='image-upload'){setDirty();$('body-length').textContent=`${$('body-editor').textContent.length.toLocaleString()} 個字元`}});document.querySelectorAll('.language-tab').forEach(tab=>{tab.addEventListener('click',()=>switchLanguage(tab.dataset.language));tab.addEventListener('keydown',languageTabKeydown)});
$('tag-input').addEventListener('input',showTagSuggestions);
$('tag-input').addEventListener('focus',showTagSuggestions);
$('tag-input').addEventListener('blur',commitTagInput);
$('tag-input').addEventListener('paste',event=>{const pasted=event.clipboardData.getData('text');if(/[、,，;；\n]/.test(pasted)){event.preventDefault();addTag(pasted)}});
$('tag-input').addEventListener('keydown',event=>{if(event.key==='ArrowDown'&&tagOptions.length){event.preventDefault();selectTagOption((activeTagOption+1)%tagOptions.length);return}if(event.key==='ArrowUp'&&tagOptions.length){event.preventDefault();selectTagOption((activeTagOption-1+tagOptions.length)%tagOptions.length);return}if(event.key==='Escape'){closeTagSuggestions();return}if(event.key==='Backspace'&&!event.currentTarget.value&&tagValues.length){event.preventDefault();tagValues.pop();renderTags();setDirty();return}if(event.key==='Enter'||event.key===','||event.key==='，'||event.key==='、'){event.preventDefault();if(activeTagOption>=0&&tagOptions[activeTagOption])addTag(tagOptions[activeTagOption]);else commitTagInput()}});
$('tag-editor').addEventListener('click',event=>{if(event.target===$('tag-editor')||event.target===$('tag-chips'))$('tag-input').focus()});
$('news-form').addEventListener('submit',e=>{e.preventDefault();capture();perform(async()=>{state=await api('draft','PUT',{data:state.data,version:state.version});setDirty(false);fill();setStatus('草稿已儲存，公開網站尚未改變。')})});
$('publish').addEventListener('click',()=>perform(async()=>{state=await api('publish','POST',{version:state.version,publishedVersion:state.publishedVersion});setDirty(false);setStatus('最新消息與活動資訊發布成功，中英文 JSON 已一起切換。')}));
$('add').addEventListener('click',()=>{const now=new Date(),id='news-'+now.toISOString().replace(/[-:T]/g,'').slice(0,14);state.data.records.push({id,collection:'news',date:now.toISOString().slice(0,10),image:'',pinned:false,locales:{zh:emptyLocale(),en:emptyLocale()}});open(id,true);setDirty();setStatus('已新增未發布的資料，請選擇類型並填寫後儲存草稿。')});
$('remove').addEventListener('click',()=>{const item=current();if(!item||!confirm(`刪除草稿「${item.locales.zh.title||item.locales.en.title||item.id}」？`))return;state.data.records=state.data.records.filter(r=>r.id!==selected);selected=null;setDirty();$('editor-view').hidden=true;$('directory-view').hidden=false;render();setStatus('已從畫面移除；按「儲存草稿」後才會生效。')});
$('image-upload').addEventListener('change',()=>{const file=$('image-upload').files[0];if(!file)return;perform(async()=>{setStatus('正在處理並上傳圖片…');const form=new FormData();form.append('image',file);const response=await fetch('/news-admin/api/image/'+encodeURIComponent(selected),{method:'POST',headers:{'X-News-Request':'1'},body:form});const value=await response.json();if(!response.ok)throw new Error(value.error||'圖片上傳失敗');$('image').value=value.url;$('image-upload-note').textContent=`新圖片已上傳（${value.width} × ${value.height}），請儲存草稿。`;setDirty();setStatus('圖片已上傳，請儲存草稿。')})});
$('reload').addEventListener('click',()=>{if(!dirty||confirm('重新載入會放棄尚未儲存的變更，確定繼續？'))perform(load)});$('back-to-list').addEventListener('click',()=>showList(true));['search','collection-filter','language-filter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));document.querySelectorAll('[data-command]').forEach(button=>button.addEventListener('mousedown',e=>{e.preventDefault();document.execCommand(button.dataset.command);setDirty()}));$('insert-link').addEventListener('click',()=>{const url=prompt('連結網址（https://…）');if(url&&/^https?:\/\//i.test(url)){document.execCommand('createLink',false,url);setDirty()}});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});perform(load);
