'use strict';
const $ = id => document.getElementById(id);
const categoryLabels = {fulltime:'專任教師',parttime:'兼任教師',practical:'實務教師',former_practical:'歷任實務教師',honorary:'名譽教授',retired:'退休教師',joint:'合聘教師',staff:'職員'};
const sharedKeys = ['email','phone','office','website','photo'];
const localizedKeys = ['name','title','expertise'];
let state, selected = null, language = 'zh', dirty = false, busy = false, creating = false, pendingRecord = null;

$('photo-upload').addEventListener('change',()=>{const file=$('photo-upload').files[0];if(!file)return;if(file.size>8*1024*1024){status('照片不可超過 8 MB',true);$('photo-upload').value='';return;}perform(async()=>{status('正在處理並上傳照片…');const result=await uploadPhoto(file);$('photo').value=result.url;$('editor-photo').src=result.url;markDirty();$('photo-upload-note').textContent=`新照片已上傳（${result.width} × ${result.height}），請按「儲存草稿」完成取代。`;status('新照片已上傳，請儲存草稿。');});});
function status(message,error=false){$('status').textContent=message;$('status').dataset.error=String(error);}
function defaultVisibility(item,lang){return lang==='zh'||item.category==='fulltime';}
function isVisible(item,lang){const value=item.locales[lang].visible;return typeof value==='boolean'?value:defaultVisibility(item,lang);}
function ensureVisibility(item){['zh','en'].forEach(lang=>{if(typeof item.locales[lang].visible!=='boolean')item.locales[lang].visible=defaultVisibility(item,lang);});}
function ensureAdditionalCategories(item){if(!Array.isArray(item.additionalCategories))item.additionalCategories=[];}
function categoriesFor(item){return [item.category,...item.additionalCategories.filter(category=>category!==item.category)];}
function isEnglishVisible(item){return isVisible(item,'en');}
function isMainSiteVisible(item){return isVisible(item,'zh');}
function record(){return creating?pendingRecord:state&&state.data.records.find(item=>item.id===selected);}
function setReleaseState(){if(!state)return;const published=state.current&&state.current.release;const matched=!dirty&&state.current&&state.current.draftVersion===state.version;$('release-state').textContent=published&&matched?'草稿已發布':'有尚未發布的草稿';$('release-state').dataset.pending=String(!matched);}
function controls(){$('publish').disabled=busy||dirty||!state;$('reload').disabled=busy;$('create-faculty').disabled=busy;$('save').disabled=busy||!dirty;$('preview').disabled=busy||dirty||creating;$('back-to-list').disabled=busy;document.querySelectorAll('#faculty-form input,#faculty-form select,#faculty-form textarea,[data-command],#insert-link,.language-tab').forEach(element=>{element.disabled=busy;});$('record-id').readOnly=!creating;$('photo-upload').disabled=busy||creating;if(record()&&record().category==='retired')$('also-retired').disabled=true;$('body-editor').contentEditable=String(!busy);}
function bodyLength(){$('body-length').textContent=`${$('body-editor').textContent.length.toLocaleString()} 個字元；內容與著作清單不截斷`;}
function markDirty(){dirty=true;controls();bodyLength();setReleaseState();}
function capture(){const current=record();if(!current)return;if(creating)current.id=$('record-id').value.trim();current.category=$('category').value;current.order=Number.parseInt($('order').value,10);const otherCategories=current.additionalCategories.filter(value=>value!=='retired'&&value!==current.category);current.additionalCategories=$('also-retired').checked&&current.category!=='retired'?[...otherCategories,'retired']:otherCategories;current.locales.zh.visible=$('visible-zh').checked;current.locales.en.visible=$('visible-en').checked;sharedKeys.forEach(key=>{current.shared[key]=$(key).value;});localizedKeys.forEach(key=>{current.locales[language][key]=$(key).value;});if($('body-editor').dataset.changed==='true')current.locales[language].bodyHtml=$('body-editor').innerHTML;}
function validateDraftRecord(current){if(!/^[a-z0-9][a-z0-9-]{0,79}$/.test(current.id))throw new Error('網址識別碼只能使用小寫英文、數字與連字號。');if(creating&&state.data.records.some(item=>item.id===current.id))throw new Error('這個網址識別碼已被使用。');if(!Number.isInteger(current.order)||current.order<1)throw new Error('請填寫正確的列表排序。');for(const lang of ['zh','en'])if(!current.locales[lang].name.trim())throw new Error(`${lang==='zh'?'中文':'英文'}姓名不能為空。`);}
function syncLanguageTabs(){document.querySelectorAll('.language-tab').forEach(tab=>{const active=tab.dataset.language===language;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;});$('language-panel').setAttribute('aria-labelledby',`language-tab-${language}`);}
function switchLanguage(next){if(next===language)return;capture();language=next;fill();}
function languageTabKeydown(event){if(!['ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();const tabs=[...document.querySelectorAll('.language-tab')];const step=event.key==='ArrowRight'?1:-1;const next=tabs[(tabs.indexOf(event.currentTarget)+step+tabs.length)%tabs.length];next.focus();switchLanguage(next.dataset.language);}
function siteBadge(element,site,visible){element.textContent=`${site}：${visible?'顯示':'不顯示'}`;element.dataset.visible=String(visible);}
function fill(){const current=record();if(!current)return;$('record-id').value=current.id;$('record-id-help').textContent=creating?'請設定儲存後不可修改的網址識別碼，例如 wang-daming。':'網址識別碼已固定；若需變更請勿直接編輯。';$('category').value=current.category;$('order').value=current.order;$('also-retired').checked=current.additionalCategories.includes('retired');$('also-retired').disabled=busy||current.category==='retired';$('visible-zh').checked=isMainSiteVisible(current);$('visible-en').checked=isEnglishVisible(current);sharedKeys.forEach(key=>{$(key).value=current.shared[key];});localizedKeys.forEach(key=>{$(key).value=current.locales[language][key];});$('body-editor').innerHTML=current.locales[language].bodyHtml;$('body-editor').dataset.changed='false';$('editor-photo').hidden=!current.shared.photo;$('editor-photo').src=current.shared.photo;$('editor-photo').alt=current.locales.zh.name;$('editor-name').textContent=creating?'新增教師':`${current.locales.zh.name} / ${current.locales.en.name}`;$('editor-meta').textContent=creating?'尚未儲存 · 預設為合聘教師':`排序 ${current.order} · ${categoryLabels[current.category]||current.category}${current.additionalCategories.includes('retired')?' · 另列退休教師':''}`;siteBadge($('editor-zh-status'),'中文主站',isMainSiteVisible(current));siteBadge($('editor-en-status'),'英文站',isEnglishVisible(current));$('photo-upload').value='';$('photo-upload-note').textContent=creating?'請先儲存新教師草稿，儲存後即可上傳照片。':'JPG、PNG 或 WebP，最大 8 MB；會自動修正方向並縮小過大的照片。';$('save').textContent=creating?'建立教師草稿':'儲存草稿';syncLanguageTabs();bodyLength();controls();}
function appendText(parent,className,value){const element=document.createElement('div');element.className=className;element.textContent=value||'—';parent.append(element);}
function makeSiteBadge(site,visible){const element=document.createElement('span');element.className='site-badge';siteBadge(element,site,visible);return element;}
function matchesFilters(item){const query=$('search').value.trim().toLocaleLowerCase('zh-Hant');const category=$('category-filter').value;const english=$('english-filter').value;if(category&&!categoriesFor(item).includes(category))return false;if(english==='visible'&&!isEnglishVisible(item))return false;if(english==='hidden'&&isEnglishVisible(item))return false;if(!query)return true;return [item.locales.zh.name,item.locales.zh.title,item.locales.zh.expertise,item.locales.en.name,item.locales.en.title,item.locales.en.expertise,item.shared.email,item.shared.phone,item.shared.office,...categoriesFor(item).map(value=>categoryLabels[value]||value)].join(' ').toLocaleLowerCase('zh-Hant').includes(query);}
function renderDirectory(){const records=[...state.data.records].sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id));const rows=records.filter(matchesFilters).map(item=>{const row=document.createElement('tr');row.tabIndex=0;row.dataset.id=item.id;row.setAttribute('aria-label',`編輯 ${item.locales.zh.name}`);const order=document.createElement('td');order.className='order-cell';order.textContent=item.order;const card=document.createElement('td');const layout=document.createElement('div');layout.className='card-data';const photo=document.createElement('img');photo.className='faculty-thumb';photo.src=item.shared.photo;photo.alt='';const names=document.createElement('div');appendText(names,'primary-data',item.locales.zh.name);appendText(names,'secondary-data',item.locales.en.name);appendText(names,'title-data',item.locales.zh.title);layout.append(photo,names);card.append(layout);const visibility=document.createElement('td');appendText(visibility,'category-label',categoryLabels[item.category]||item.category);if(item.additionalCategories.length)appendText(visibility,'secondary-data',`另列：${item.additionalCategories.map(value=>categoryLabels[value]||value).join('、')}`);const badges=document.createElement('div');badges.className='site-badges';badges.append(makeSiteBadge('中文',isMainSiteVisible(item)),makeSiteBadge('英文',isEnglishVisible(item)));visibility.append(badges);const expertise=document.createElement('td');appendText(expertise,'compact-copy',item.locales.zh.expertise);appendText(expertise,'compact-copy muted-copy',item.locales.en.expertise);const contact=document.createElement('td');appendText(contact,'contact-line',item.shared.email);appendText(contact,'contact-line',item.shared.phone);appendText(contact,'contact-line muted-copy',item.shared.office);const action=document.createElement('td');action.className='action-cell';const button=document.createElement('button');button.type='button';button.className='edit-button';button.textContent='編輯';button.addEventListener('click',event=>{event.stopPropagation();openEditor(item.id,true);});action.append(button);row.append(order,card,visibility,expertise,contact,action);row.addEventListener('click',()=>openEditor(item.id,true));row.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openEditor(item.id,true);}});return row;});$('faculty-rows').replaceChildren(...rows);$('empty-result').hidden=rows.length>0;$('total-count').textContent=records.length;$('zh-count').textContent=records.filter(isMainSiteVisible).length;$('en-count').textContent=records.filter(isEnglishVisible).length;}
function showDirectory(updateHistory=false){if(dirty&&!confirm('返回清單會放棄尚未儲存的變更，確定繼續？'))return false;dirty=false;selected=null;creating=false;pendingRecord=null;$('editor-view').hidden=true;$('directory-view').hidden=false;$('preview-section').hidden=true;renderDirectory();if(updateHistory)history.pushState({faculty:null},'',location.pathname);controls();return true;}
function openEditor(id,updateHistory=false){if(!state.data.records.some(item=>item.id===id))return;if(dirty&&selected!==id&&!confirm('切換教師會放棄尚未儲存的變更，確定繼續？'))return;dirty=false;creating=false;pendingRecord=null;selected=id;language='zh';$('directory-view').hidden=true;$('editor-view').hidden=false;$('preview-section').hidden=true;fill();if(updateHistory){const url=new URL(location.href);url.searchParams.set('id',id);history.pushState({faculty:id},'',url);}controls();window.scrollTo({top:0,behavior:'instant'});}
function createFaculty(){const jointOrders=state.data.records.filter(item=>item.category==='joint').map(item=>item.order);pendingRecord={id:'',order:Math.max(500,...jointOrders)+1,category:'joint',additionalCategories:[],shared:{email:'',phone:'',office:'',website:'',photo:''},locales:{zh:{name:'',title:'',expertise:'',bodyHtml:'',originalUrl:'',visible:false},en:{name:'',title:'',expertise:'',bodyHtml:'',originalUrl:'',visible:false}}};creating=true;selected=null;language='zh';dirty=true;$('directory-view').hidden=true;$('editor-view').hidden=false;$('preview-section').hidden=true;fill();history.pushState({facultyNew:true},'',`${location.pathname}?new=1`);status('正在建立合聘教師草稿。中英文預設都不公開。');$('record-id').focus();}
function populateFilters(){const used=[...new Set(state.data.records.map(item=>item.category))];used.sort((a,b)=>state.data.records.find(item=>item.category===a).order-state.data.records.find(item=>item.category===b).order);$('category-filter').append(...used.map(category=>{const option=document.createElement('option');option.value=category;option.textContent=categoryLabels[category]||category;return option;}));}
async function api(path,method='GET',data){const response=await fetch('/faculty/api/'+path,{method,headers:{'Content-Type':'application/json','X-Faculty-Request':'1'},body:data?JSON.stringify(data):undefined,cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error||'請求失敗');return value;}
async function uploadPhoto(file){const form=new FormData();form.append('photo',file);const response=await fetch(`/faculty/api/photo/${encodeURIComponent(selected)}`,{method:'POST',headers:{'X-Faculty-Request':'1'},body:form,cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error||'照片上傳失敗');return value;}
async function load(){state=await api('draft');if(!state.data)throw new Error('尚未匯入教師資料。');state.data.records.forEach(item=>{ensureVisibility(item);ensureAdditionalCategories(item);});dirty=false;$('category-filter').replaceChildren(Object.assign(document.createElement('option'),{value:'',textContent:'所有教師類別'}));populateFilters();setReleaseState();const requestedId=new URL(location.href).searchParams.get('id');if(requestedId&&state.data.records.some(item=>item.id===requestedId))openEditor(requestedId,false);else showDirectory(false);status('已載入教師資料。勾選狀態會在發布後更新公開教師清單。');}
async function perform(fn){if(busy)return;busy=true;controls();try{await fn();}catch(error){status(error.message,true);}finally{busy=false;controls();}}
$('faculty-form').addEventListener('input',event=>{if(event.target.id!=='photo-upload')markDirty();});$('body-editor').addEventListener('input',()=>{$('body-editor').dataset.changed='true';});$('category').addEventListener('change',()=>{capture();fill();markDirty();});$('order').addEventListener('change',()=>{capture();fill();markDirty();});document.querySelectorAll('.language-tab').forEach(tab=>{tab.addEventListener('click',()=>switchLanguage(tab.dataset.language));tab.addEventListener('keydown',languageTabKeydown);});
$('faculty-form').addEventListener('submit',event=>{event.preventDefault();capture();perform(async()=>{const current=record();validateDraftRecord(current);const wasCreating=creating;const payload=wasCreating?{...state.data,records:[...state.data.records,current]}:state.data;state=await api('draft','PUT',{data:payload,version:state.version});if(wasCreating){creating=false;pendingRecord=null;selected=current.id;history.replaceState({faculty:selected},'',`${location.pathname}?id=${encodeURIComponent(selected)}`);}dirty=false;fill();setReleaseState();status(wasCreating?'新教師草稿已建立。現在可上傳照片、預覽，完成後再設為公開。':'草稿已儲存，公開版本尚未改變。');});});
$('publish').addEventListener('click',()=>perform(async()=>{state=await api('publish','POST',{version:state.version,publishedVersion:state.publishedVersion});setReleaseState();status('教師資料發布成功，中英文教師清單已更新。');}));
$('reload').addEventListener('click',()=>{if(!dirty||confirm('重新載入會放棄尚未儲存的變更，確定繼續？'))perform(load);});$('create-faculty').addEventListener('click',createFaculty);$('back-to-list').addEventListener('click',()=>showDirectory(true));$('preview').addEventListener('click',()=>{$('preview-section').hidden=false;$('preview-frame').src=`/faculty/preview/?draft=1&id=${encodeURIComponent(selected)}&lang=${language}`;$('preview-section').scrollIntoView({behavior:'smooth'});});$('close-preview').addEventListener('click',()=>{$('preview-section').hidden=true;$('preview-frame').src='about:blank';});
['search','category-filter','english-filter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderDirectory));document.querySelectorAll('[data-command]').forEach(button=>button.addEventListener('mousedown',event=>{event.preventDefault();document.execCommand(button.dataset.command);$('body-editor').dataset.changed='true';markDirty();}));$('insert-link').addEventListener('click',()=>{const url=prompt('連結網址（https://…）');if(url&&/^https?:\/\//i.test(url)){document.execCommand('createLink',false,url);$('body-editor').dataset.changed='true';markDirty();}});
window.addEventListener('popstate',()=>{const requestedId=new URL(location.href).searchParams.get('id');if(requestedId)openEditor(requestedId,false);else showDirectory(false);});window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});perform(load);
